services:
  airflow-init:
    build: .
    user: "0:0"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - PYTHONPATH=/opt/airflow/project
    volumes:
      - airflow_data:/opt/airflow
      - ../../dags:/opt/airflow/dags
      - ../../:/opt/airflow/project
      - ../../mlruns:/app/mlruns
      - ../../:/app
    entrypoint: >
      /bin/bash -c "airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"

  airflow-webserver:
    build: .
    depends_on:
      - airflow-init
    user: "0:0"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__PYTHON_COMMAND=/usr/local/bin/python -W ignore::SyntaxWarning
      - PYTHONPATH=/opt/airflow/project
    volumes:
      - airflow_data:/opt/airflow
      - ../../dags:/opt/airflow/dags
      - ../../:/opt/airflow/project
      - ../../mlruns:/app/mlruns
      - ../../:/app
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      - airflow-init
    user: "0:0"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - PYTHONPATH=/opt/airflow/project
    volumes:
      - airflow_data:/opt/airflow
      - ../../dags:/opt/airflow/dags
      - ../../:/opt/airflow/project
      - ../../mlruns:/app/mlruns
      - ../../:/app
    command: scheduler

volumes:
  airflow_data:
